using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.Entity;

namespace TDU.CMS2
{
    public partial class Form1 : DevExpress.XtraEditors.XtraForm
    {
        public Form1()
        {
            InitializeComponent();
            initBingdings();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext

            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
        }

        private void initBingdings()
        {
            using (TDU.CMS2.DataBase.CMSDbContext dbContext = new TDU.CMS2.DataBase.CMSDbContext())
            {
                dbContext.CardRequests.LoadAsync().ContinueWith(loadTask =>
                {
                    // Bind data to control when loading complete
                    cardRequestsBindingSource.DataSource = dbContext.CardRequests.Local.ToBindingList();
                }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
                //Student stud = new Student() { StudentName = "New Student" };

                //ctx.Students.Add(stud);
                ctx.SaveChanges();
            }
        }
    }
}