using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.Entity;
using System.IO;
using DevExpress.Data.WcfLinq.Helpers;
using TDU.CMS2.DataBase;
using NPOI.SS.UserModel;
using TDU.CMS2.DataModels;

namespace TDU.CMS2
{
    public partial class Form1 : DevExpress.XtraEditors.XtraForm
    {
        private CMSDbContext dbContext;
        private List<CardRequest> cList;

        public Form1()
        {
            InitializeComponent();
            initBingdings();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            dbContext = new TDU.CMS2.DataBase.CMSDbContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //dbContext.CardRequests.LoadAsync().ContinueWith(loadTask =>
            //{
            //    // Bind data to control when loading complete
            //    cardRequestsBindingSource1.DataSource = dbContext.CardRequests.Local.Where(c => dbContext.Entry(c).State == EntityState.Added).ToList();
            //    //.ToBindingList();
            //    //.Where(c => dbContext.Entry(c).State == EntityState.Added).ToList();
            //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            }

        private void initBingdings()
        {
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //dbContext.CardRequests.AddRange(cList);
            //dbContext.SaveChanges();
            gridView1.PostEditor();
            MessageBox.Show(cList.Where(x => x.Cif == "0011177031").FirstOrDefault().Code);
        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (openFileDialog1.ShowDialog() == DialogResult.OK)
            {
                //MessageBox.Show(openFileDialog1.FileName);
                FileStream fs = File.OpenRead(openFileDialog1.FileName);
                IWorkbook wb = WorkbookFactory.Create(fs);
                //DateTime dt = wb.GetSheetAt(0).GetRow(1).GetCell(6).DateCellValue;
                //MessageBox.Show(("Value of Cell B2: " + dt.ToString()));
                cList = new List<CardRequest>();
                ISheet i = wb.GetSheetAt(0);
                for (int rowindex = 1; rowindex < i.LastRowNum; rowindex++)
                {
                    var c = new CardRequest();
                    c.CardNumber = i.GetRow(rowindex).GetCell(0).StringCellValue.Trim();
                    c.CardHolder = i.GetRow(rowindex).GetCell(1).StringCellValue.Trim();
                    c.RequestDate = i.GetRow(rowindex).GetCell(7).DateCellValue;
                    c.Cif = i.GetRow(rowindex).GetCell(9).StringCellValue.Trim();
                    c.CardLocation = 0;
                    c.PinLocation = 0;
                    c.EmployeeName = "Nguyen Thi Hong Dao";
                    c.State = RequestState.Producing;
                    c.Type = RequestType.Issue;
                    c.Code = i.GetRow(rowindex).GetCell(14).StringCellValue.Trim();
                    ;
                    cList.Add(c);
                }
                //cardRequestsBindingSource1.DataSource = dbContext.CardRequests.Local.Where(d => dbContext.Entry(d).State == EntityState.Added).ToList();}
                cardRequestsBindingSource1.DataSource = cList;
            }
        }
    }
}